/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/jetpack_trippy.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Polygon.geometry} material={materials['Mat.1']} position={[-0.91, 0.1, -3.39]} rotation={[-Math.PI, -0.51, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/jetpack_trippy.glb')
